version: '3.7'

networks:
  default:
    name: docker-proxy-overlay
    external: true


services:
  movie_service:
    build: movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    environment:
      - VIRTUAL_HOST=api-movie.dev
      - VIRTUAL_PORT=8000
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db
      - keycloak
    ports:
      - 8081:8000

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    environment:
      - VIRTUAL_HOST=api-cast.dev
      - VIRTUAL_PORT=8000
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    depends_on:
      - cast_db

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev

  nginx:
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=movie.ng
      - VIRTUAL_PORT=8080
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

  keycloak_db:
    image: postgis/postgis:14-3.3-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data/

  keycloak:
    depends_on:
      - keycloak_db
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      VIRTUAL_HOST: keycloak.loc
      VIRTUAL_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://keycloak_db:5432/keycloak"
      KC_METRICS_ENABLED: true
    ports:
      - 7070:8080
    volumes:
      - keycloak-volume:/opt/jboss/keycloak/standalone/data
      - ./keycloak/my-realm.json:/tmp/my-realm.json:ro


volumes:
  postgres_data_movie:
  postgres_data_cast:
  postgres_data_keycloak:
  keycloak-volume:
